### ISSUE TITLE
Getting bad request response

### ISSUE THREAD

**Issue by elmaso** [udacity/reviewer-dashboard-feedback#18]
When I try to enter queue, (both one review or keep my queue full) I get a red messages at the bottom   "Error creating submission request (Bad Request)"  Im using Safari on a Mac OS Sierra

**Comment by YCSU** [comment]
I am also experiencing the same problem and do not get any assignment assigned

**Comment by JustinHeaton** [comment]
I am still unable to enter the queue because of this bad request error. In dev tools I see the following:
```
SubmissionRequest body:  {"projects":[{"project_id":248,"language":"en-us"},{"project_id":248,"language":"zh-cn"},{"project_id":248,"language":"zh-cn"},{"project_id":239,"language":"en-us"},{"project_id":239,"language":"zh-cn"},{"project_id":239,"language":"zh-cn"},{"project_id":237,"language":"en-us"},{"project_id":237,"language":"zh-cn"},{"project_id":237,"language":"zh-cn"}]}
```
Somehow the Chinese language project/language pairs are being duplicated. Could this be a reason for the bad request?
