### ISSUE TITLE
Notifcation of a New Review in browser

### ISSUE THREAD

**Issue by kellim** [udacity/reviewer-dashboard-feedback#24]
New reviews don't show up in the Reviews Dashboard until I reload the page and it would be nice if they did. Also it would be nice if it made a sound or notification of a review even when you're in another browser tab or app.

**Comment by Digizard** [comment]
I suggested a  desktop notification, like Slack does for messages, in #19.

**Comment by kellim** [comment]
Unfortunately I missed your Desktop notifications issue when I posted this. Desktop notifications like Slack has would be perfect. :)
