### ISSUE TITLE
Queue Turning off for unknown reasons

### ISSUE THREAD

**Issue by kellim** [udacity/reviewer-dashboard-feedback#26]
The queue turns off (it takes me out of the queue for reviews) sometimes before "Time in Queue" gets to 0 - in fact, it still should have had hours left. I notice this happens as I'm doing reviews but not sure the exact thing that causes it. And I have not gotten to the limit of having 5 reviews at a time under "To Do" yet. Someone else also made a post about it in the Udacity Mentors Slack chat in #reviews-bugs but it looks like it hasn't been reported here yet.

**Comment by Digizard** [comment]
Is it only turning off before you hit 5? Or at other times, too?

Might be helpful for narrowing down the cause of the issue to have an idea of what leads up to it.

**Comment by kellim** [comment]
I haven't hit 5 yet, it might have been 4 one time and less another when it happened.

**Comment by Hadrien-lcrx** [comment]
This issue is not resolved. My queue has been deactivated several times in the past days, before reaching the 5 projects limit.
