### ISSUE TITLE
Old Onboarding Link using my 5th spot

### ISSUE THREAD

**Issue by nikifi** [udacity/reviewer-dashboard-feedback#30]
Years ago I applied to be a reviewer for interviewing practice. That was never completed. It now shows up in my to-do with all the other reviews. However, my actual review queue seems to never move past 4, and it appears as if the on boarding link for the interview practice is using the fifth spot. Also, there is no way to withdraw my application for that interview review.

**Comment by nikifi** [comment]
I got the old onboarding review removed and my review queue still never move past 4. So perhaps the issue isn't this old on boarding link - it is that the queue seems to turn off before it is full.

**Comment by amandaraney** [comment]
There was an issue where some reviewers were only having four submission requests filled, not five. It was not related to the onboarding review - the issue has since been resolved! Moving this to done.
