### ISSUE TITLE
Queue Stops after 4 projects

### ISSUE THREAD

**Issue by thedurphy** [udacity/reviewer-dashboard-feedback#32]
The queue stops after the 4th project has been assigned.  I can then add the 5th project manually but it doesn't automatically do it.

**Comment by Digizard** [comment]
Possibly a duplicate of #26, though I'm not 100% sure.

**Comment by nikifi** [comment]
I have this problem too

**Comment by sudhirkhanger** [comment]
@amandastinesUdacity It doesn't look like this issue has been resolved. I just encountered it.

**Comment by thedurphy** [comment]
@cali-step @amandastinesUdacity I just encountered this issue again.  I sent screenshot proof along with a video of having to manually assign the 5th submission.  Please open this issue again.

**Comment by nikifi** [comment]
I am still encountering it too
