### ISSUE TITLE
TOTAL EARNINGS under YOUR STATS is not showing the right amount of total earnings compared the project table

### ISSUE THREAD

**Issue by Robert-Barry** [udacity/reviewer-dashboard-feedback#6]

**Comment by gabraganca** [comment]
In my case, it seems to be missing the Can't Review ones.

**Comment by ayush1095** [comment]
Yes, total earnings are not correct.

**Comment by trolster** [comment]
For me it also fits with the result omitting the "Can't Review" submissions, just like @gabraganca said.

**Comment by elnobun** [comment]
My `Total Earnings` is off by **$185** for January, and **$28** for February.

**Comment by KnHuq** [comment]
Yeah, the problem is with the Can't Review ones.

**Comment by sam14-droid** [comment]
How much do we get pay per review for standard nanodegree such as self driving car, machine learning, front end, andrpid or robotics?
