### ISSUE TITLE
Offer False new certification opportunity

### ISSUE THREAD

**Issue by yannrs** [udacity/reviewer-dashboard-feedback#7]

**Comment by elmaso** [comment]
When you click on the new opportunity link you get this messages

Sorry, this opportunity to become a reviewer is not available.

**Comment by kartikarora** [comment]
@elmaso Write to review-support@udacity.com. They'll help you.

**Comment by romcabrera** [comment]
Even after this was marked as "closed" I'm still seeing "ONBOARD NOW" projects which I cannot access.

**Comment by romcabrera** [comment]
Update: this is fixed now.
