### ISSUE TITLE
Mobile notifications (iOS)

### ISSUE THREAD

**Issue by kartikarora** [udacity/reviewer-dashboard-feedback#9]
With `urcli`, we can add pushbullet API key to get push notifications whenever a new review was assigned. Something similar in the new dashboard would be appreciated.

**Comment by gregypooh** [comment]
+1 would love this in the new dashboard since this is a major part of workflow.

**Comment by thePsguy** [comment]
**+1** This, I believe, really helps bring down the turnaround time for the reviews. (https://docs.pushbullet.com/#api-quick-start)

**Comment by ddrm86** [comment]
+1 Some kind of notification system would be nice (email, browser notification, cellphone...) Sometimes I forget to check the browser Window and reviews stay there waiting...

**Comment by thePsguy** [comment]
Has this issue been resolved in some form?

**Comment by amandaraney** [comment]
We're working on mobile notifications now! Sorry, I dragged this one column too far over to done. Thanks for flagging.
